### ISSUE TITLE
Failed to suspend the page with screen capture on

### ISSUE THREAD

**Issue by sergiorussia** [deanoemcke/thegreatsuspender#657]
Hi!
Steps to reproduce:
1. goto http://en.miui.com/forum.php
2. try to suspend the tab
3. the tab won't suspend, Console says "Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported."

Reproducible: stable

**Comment by Firecul** [comment]
Sorry suspends fine for me.

**Comment by sergiorussia** [comment]
reproduced on both my machines.
here are few more details:

chrome console log:
```
contentscript.js:149 canvas: [object HTMLCanvasElement]
contentscript.js:150 Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at Object.onrendered (chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/js/contentscript.js:150:46)
    at Object.o.complete (file:///home/sergio/.config/google-chrome/Default/Extensions/klbibkeccnjlkjkiokjodocebajanakg/6.30_0/js/html2canvas.min.js:8:2419)
    at o (file:///home/sergio/.config/google-chrome/Default/Extensions/klbibkeccnjlkjkiokjodocebajanakg/6.30_0/js/html2canvas.min.js:7:28352)
    at Image.e.onload (file:///home/sergio/.config/google-chrome/Default/Extensions/klbibkeccnjlkjkiokjodocebajanakg/6.30_0/js/html2canvas.min.js:7:29918)
onrendered @ contentscript.js:150
o.complete @ html2canvas.min.js:8
o @ html2canvas.min.js:7
e.onload @ html2canvas.min.js:7
```

Chrome 64, Ubuntu 16.04, adblockers were turned off for the test

**Comment by deanoemcke** [comment]
I have been able to reliably reproduce this.
It's important to note that it only occurs if the 'screen capturing' option is turned on.
It is an issue with the html2canvas library that I use. I have raised an issue on that project: https://github.com/niklasvh/html2canvas/issues/1466

The current alpha build of TGS will not fail to suspend on this page, however, it will not be able to produce the screenshot and will just show a normal blank suspended tab page.

**Comment by deanoemcke** [comment]
People have suggested using https://github.com/tsayen/dom-to-image instead of html2canvas (as a solution to the above issue).
I will look into this as part of: https://github.com/deanoemcke/thegreatsuspender/issues/677

**Comment by deanoemcke** [comment]
I have added support for the dom-to-image screencapture library. Although it appears to be much slower, and also less reliable than html2canvas.
You can switch to the dom-to-image library by going to the extension debug.html page (chrome-extension://<extension-id>/debug.html) and toggling the "useAlternateScreenCaptureLib" option.

**Comment by sergiorussia** [comment]
nice, thanks, will check it out

**Comment by Pascal666** [comment]
Hopefully this change also fixes suspending https://9gag.com
